# Project Euler : Problem 2 ->https://projecteuler.net/problem=2 One line
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import time

def fibo(list):
	list.append(list[-1]+list[-2])
	return list

restime = []
for j in range(10):
	time1 = time.clock()
	fibolist = [1,2]
	sumfiboeven = sum([x for x in [fibo(fibolist)[-1] for i in range(400000) if fibolist[-1] < 3500000] if x%2==0]) + 2
	time2 = time.clock()
	restime.append(time2-time1)
print sumfiboeven
print fibolist[-1]
print sum(restime)/float(len(restime))
